---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    ENABLE_LEGACY_ORA: !!null
    EDXAPP_USE_MICROSITES: true
    EDXAPP_MICROSITE_ROOT_DIR: "{{ edxapp_app_dir }}/edx-microsites"
    EDXAPP_EDVERA_SYSTEM_TOKEN: "placeholder"
    EDXAPP_MICROSITE_CONFIGURATION:
      wqu:
        domain_prefix: "wqu"
        university: "wqu"
        SITE_NAME: "wqu.edx.cyanna.com"
        platform_name: "WorldQuant University"
        css_overrides_file: "wqu/css/style.css"
        logo_image_url: "wqu/images/logo.png"
      wquiframe:
        domain_prefix: "wquiframe"
        university: "wquiframe"
        SITE_NAME: "wquiframe.edx.cyanna.com"
        platform_name: "WorldQuant University"
        css_overrides_file: "in-iframe.css"
        logo_image_url: "wquiframe/images/logo.png"

  roles:
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - ora
      - xqueue
      nginx_default_sites:
      - lms
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - role: ora
      when: ENABLE_LEGACY_ORA
    - certs
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
