---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # These should stay false for the public AMI
    COMMON_ENABLE_DATADOG: False
    EDXAPP_LMS_BASE: "edx.cyanna.com"
    EDXAPP_PREVIEW_LMS_BASE: "edx.cyanna.com"
    COMMON_ENABLE_SPLUNKFORWARDER: False
    ENABLE_LEGACY_ORA: !!null
    EDXAPP_USE_MICROSITES: true
    EDXAPP_MICROSITE_ROOT_DIR: "{{ edxapp_app_dir }}/edx-microsites"
    EDXAPP_EDVERA_SYSTEM_TOKEN: "placeholder"
    EDXAPP_MICROSITE_CONFIGURATION:
      learn:
        domain_prefix: "learn"
        university: "learn"
        SITE_NAME: "learn.worldquantuniversity.org"
        platform_name: "WorldQuant University"
        css_overrides_file: "learn/css/style.css"
        logo_image_url: "learn/images/logo.png"
      iframewqu:
        domain_prefix: "iframewqu"
        university: "iframewqu"
        SITE_NAME: "iframewqu.edx.cyanna.com"
        platform_name: "WorldQuant University"
        css_overrides_file: "iframe.css"

  roles:
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - forum
      - ora
      - xqueue
      nginx_default_sites:
      - lms
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - role: ora
      when: ENABLE_LEGACY_ORA
    - certs
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
